### PR TITLE
created index.html wrote name

### PR DESCRIPTION
**Pull request by ScottFeichter**
Created index.html wrote name

### CODE REVIEW

**Comment by akosasante** [comment]
Looks great Scott 👍 

I think in future assignments, you'll want to hold off on merging the PR until after it's been reviewed. That'll better simulate the usual dev workflow and also will make it easier to make changes to the branch if there's changes requested on the part of the assignment reviewer. 

Before we continue on to the next lessons, I believe you'll want to move your `index.html` file. Right now, you have it in `instructions/section-2/index.html` but we'll want it to be in the project's root directory so that we can keep building on it in future sections (https://github.com/ScottFeichter/intro-to-programming-dorado/blob/main/instructions/rubric.md).

something like:

```
intro-to-programming-dorado/
  ├─ instructions/
  ├─ README.md
  ├─ index.html
```

**Comment by akosasante** [comment]
Please let me know what concepts with `git` and `Github` you found tricky or would like to review; or any questions you had with this assignment 🙂

**Comment by ScottFeichter** [comment]
HI there - 

If I move it on my local machine I will then need to do a git add . 

 then a git commit -m correct? Then I must push these changes to GitHub - is this correct?

Thank you,

Scott

**Comment by akosasante** [comment]
Yes those would be the correct steps 👍

**Comment by ScottFeichter** [comment]
Kind of all of git and GitHub is a struggle for me. Is it possible to do a 1:1 zoom with you?

**Pull request merged**
